# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/designer/simulations/biomeng321lab1.ui'
#
# Created: Mon Feb 15 14:24:00 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Biomeng321Lab1(object):
    def setupUi(self, Biomeng321Lab1):
        Biomeng321Lab1.setObjectName("Biomeng321Lab1")
        Biomeng321Lab1.resize(855, 728)
        self.gridLayout = QtGui.QGridLayout(Biomeng321Lab1)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(Biomeng321Lab1)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditInvariant1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditInvariant1.setObjectName("lineEditInvariant1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditInvariant1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditInvariant2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditInvariant2.setObjectName("lineEditInvariant2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditInvariant2)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditInvariant3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditInvariant3.setObjectName("lineEditInvariant3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditInvariant3)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditHydrostaticPressure = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditHydrostaticPressure.setObjectName("lineEditHydrostaticPressure")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditHydrostaticPressure)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 1, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidgetRightCauchyGreenDeformation = QtGui.QTableWidget(self.groupBox_7)
        self.tableWidgetRightCauchyGreenDeformation.setObjectName("tableWidgetRightCauchyGreenDeformation")
        self.tableWidgetRightCauchyGreenDeformation.setColumnCount(0)
        self.tableWidgetRightCauchyGreenDeformation.setRowCount(0)
        self.tableWidgetRightCauchyGreenDeformation.horizontalHeader().setVisible(False)
        self.tableWidgetRightCauchyGreenDeformation.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.tableWidgetRightCauchyGreenDeformation, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidgetCauchyStress = QtGui.QTableWidget(self.groupBox_4)
        self.tableWidgetCauchyStress.setObjectName("tableWidgetCauchyStress")
        self.tableWidgetCauchyStress.setColumnCount(0)
        self.tableWidgetCauchyStress.setRowCount(0)
        self.tableWidgetCauchyStress.horizontalHeader().setVisible(False)
        self.tableWidgetCauchyStress.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.tableWidgetCauchyStress, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 1, 2, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidgetSecondPiolaKirchoffStress = QtGui.QTableWidget(self.groupBox_8)
        self.tableWidgetSecondPiolaKirchoffStress.setObjectName("tableWidgetSecondPiolaKirchoffStress")
        self.tableWidgetSecondPiolaKirchoffStress.setColumnCount(0)
        self.tableWidgetSecondPiolaKirchoffStress.setRowCount(0)
        self.tableWidgetSecondPiolaKirchoffStress.horizontalHeader().setVisible(False)
        self.tableWidgetSecondPiolaKirchoffStress.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tableWidgetSecondPiolaKirchoffStress, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidgetGreenLagrangeStrain = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidgetGreenLagrangeStrain.setObjectName("tableWidgetGreenLagrangeStrain")
        self.tableWidgetGreenLagrangeStrain.setColumnCount(0)
        self.tableWidgetGreenLagrangeStrain.setRowCount(0)
        self.tableWidgetGreenLagrangeStrain.horizontalHeader().setVisible(False)
        self.tableWidgetGreenLagrangeStrain.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.tableWidgetGreenLagrangeStrain, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidgetDeformationGradient = QtGui.QTableWidget(self.groupBox_6)
        self.tableWidgetDeformationGradient.setObjectName("tableWidgetDeformationGradient")
        self.tableWidgetDeformationGradient.setColumnCount(0)
        self.tableWidgetDeformationGradient.setRowCount(0)
        self.tableWidgetDeformationGradient.horizontalHeader().setVisible(False)
        self.tableWidgetDeformationGradient.verticalHeader().setVisible(False)
        self.gridLayout_8.addWidget(self.tableWidgetDeformationGradient, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Biomeng321Lab1)
        QtCore.QMetaObject.connectSlotsByName(Biomeng321Lab1)

    def retranslateUi(self, Biomeng321Lab1):
        Biomeng321Lab1.setWindowTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Biomeng321 Lab1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Invariants", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Biomeng321Lab1", "I1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Biomeng321Lab1", "I2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Biomeng321Lab1", "I3:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Hydrostatic Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Biomeng321Lab1", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Right Cauchy-Green Deformation Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Cauchy Stress Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Second Piola-Kirchhoff Stress Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Green-Lagrange Strain Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Biomeng321Lab1", "Deformation Gradient Tensor", None, QtGui.QApplication.UnicodeUTF8))

