# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/designer/simulations/biomeng321lab2.ui'
#
# Created: Fri Mar  4 13:31:07 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Biomeng321Lab2(object):
    def setupUi(self, shared_opengl_widget, Biomeng321Lab2):
        Biomeng321Lab2.setObjectName("Biomeng321Lab2")
        Biomeng321Lab2.resize(855, 731)
        self.verticalLayout = QtGui.QVBoxLayout(Biomeng321Lab2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(Biomeng321Lab2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.tableWidgetDeformationGradient = QtGui.QTableWidget(self.groupBox_6)
        self.tableWidgetDeformationGradient.setObjectName("tableWidgetDeformationGradient")
        self.tableWidgetDeformationGradient.setColumnCount(0)
        self.tableWidgetDeformationGradient.setRowCount(0)
        self.tableWidgetDeformationGradient.horizontalHeader().setVisible(False)
        self.tableWidgetDeformationGradient.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidgetDeformationGradient)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditInvariant1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditInvariant1.setObjectName("lineEditInvariant1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditInvariant1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditInvariant2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditInvariant2.setObjectName("lineEditInvariant2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditInvariant2)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditInvariant3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditInvariant3.setObjectName("lineEditInvariant3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditInvariant3)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.tableWidgetRightCauchyGreenDeformation = QtGui.QTableWidget(self.groupBox_7)
        self.tableWidgetRightCauchyGreenDeformation.setObjectName("tableWidgetRightCauchyGreenDeformation")
        self.tableWidgetRightCauchyGreenDeformation.setColumnCount(0)
        self.tableWidgetRightCauchyGreenDeformation.setRowCount(0)
        self.tableWidgetRightCauchyGreenDeformation.horizontalHeader().setVisible(False)
        self.tableWidgetRightCauchyGreenDeformation.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tableWidgetRightCauchyGreenDeformation)
        self.gridLayout_2.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.tableWidgetGreenLagrangeStrainReference = QtGui.QTableWidget(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetGreenLagrangeStrainReference.sizePolicy().hasHeightForWidth())
        self.tableWidgetGreenLagrangeStrainReference.setSizePolicy(sizePolicy)
        self.tableWidgetGreenLagrangeStrainReference.setObjectName("tableWidgetGreenLagrangeStrainReference")
        self.tableWidgetGreenLagrangeStrainReference.setColumnCount(0)
        self.tableWidgetGreenLagrangeStrainReference.setRowCount(0)
        self.tableWidgetGreenLagrangeStrainReference.horizontalHeader().setVisible(False)
        self.tableWidgetGreenLagrangeStrainReference.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.tableWidgetGreenLagrangeStrainReference)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.tableWidgetGreenLagrangeStrainFibre = QtGui.QTableWidget(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetGreenLagrangeStrainFibre.sizePolicy().hasHeightForWidth())
        self.tableWidgetGreenLagrangeStrainFibre.setSizePolicy(sizePolicy)
        self.tableWidgetGreenLagrangeStrainFibre.setObjectName("tableWidgetGreenLagrangeStrainFibre")
        self.tableWidgetGreenLagrangeStrainFibre.setColumnCount(0)
        self.tableWidgetGreenLagrangeStrainFibre.setRowCount(0)
        self.tableWidgetGreenLagrangeStrainFibre.horizontalHeader().setVisible(False)
        self.tableWidgetGreenLagrangeStrainFibre.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.tableWidgetGreenLagrangeStrainFibre)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.widgetSceneviewer = SceneviewerWidget(self.groupBox, shared_opengl_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSceneviewer.sizePolicy().hasHeightForWidth())
        self.widgetSceneviewer.setSizePolicy(sizePolicy)
        self.widgetSceneviewer.setObjectName("widgetSceneviewer")
        self.gridLayout_3.addWidget(self.widgetSceneviewer, 0, 1, 2, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditHydrostaticPressure = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditHydrostaticPressure.setObjectName("lineEditHydrostaticPressure")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditHydrostaticPressure)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_21 = QtGui.QLabel(self.groupBox_8)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.tableWidgetSecondPiolaKirchoffStressReference = QtGui.QTableWidget(self.groupBox_8)
        self.tableWidgetSecondPiolaKirchoffStressReference.setObjectName("tableWidgetSecondPiolaKirchoffStressReference")
        self.tableWidgetSecondPiolaKirchoffStressReference.setColumnCount(0)
        self.tableWidgetSecondPiolaKirchoffStressReference.setRowCount(0)
        self.tableWidgetSecondPiolaKirchoffStressReference.horizontalHeader().setVisible(False)
        self.tableWidgetSecondPiolaKirchoffStressReference.verticalHeader().setVisible(False)
        self.horizontalLayout_5.addWidget(self.tableWidgetSecondPiolaKirchoffStressReference)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.label_22 = QtGui.QLabel(self.groupBox_8)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.label_20 = QtGui.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.tableWidgetSecondPiolaKirchoffStressFibre = QtGui.QTableWidget(self.groupBox_8)
        self.tableWidgetSecondPiolaKirchoffStressFibre.setObjectName("tableWidgetSecondPiolaKirchoffStressFibre")
        self.tableWidgetSecondPiolaKirchoffStressFibre.setColumnCount(0)
        self.tableWidgetSecondPiolaKirchoffStressFibre.setRowCount(0)
        self.tableWidgetSecondPiolaKirchoffStressFibre.horizontalHeader().setVisible(False)
        self.tableWidgetSecondPiolaKirchoffStressFibre.verticalHeader().setVisible(False)
        self.horizontalLayout_6.addWidget(self.tableWidgetSecondPiolaKirchoffStressFibre)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidgetCauchyStress = QtGui.QTableWidget(self.groupBox_4)
        self.tableWidgetCauchyStress.setObjectName("tableWidgetCauchyStress")
        self.tableWidgetCauchyStress.setColumnCount(0)
        self.tableWidgetCauchyStress.setRowCount(0)
        self.tableWidgetCauchyStress.horizontalHeader().setVisible(False)
        self.tableWidgetCauchyStress.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.tableWidgetCauchyStress, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_10, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Biomeng321Lab2)
        QtCore.QMetaObject.connectSlotsByName(Biomeng321Lab2)

    def retranslateUi(self, Biomeng321Lab2):
        Biomeng321Lab2.setWindowTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Biomeng321 Lab2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Solution", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Strain Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Deformation Gradient Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Biomeng321Lab2", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Biomeng321Lab2", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Invariants", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Biomeng321Lab2", "I1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Biomeng321Lab2", "I2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Biomeng321Lab2", "I3:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Right Cauchy-Green Deformation Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Biomeng321Lab2", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Biomeng321Lab2", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Green-Lagrange Strain Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Biomeng321Lab2", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Biomeng321Lab2", "(ref)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Biomeng321Lab2", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Biomeng321Lab2", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Biomeng321Lab2", "(fib)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Biomeng321Lab2", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Stress Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Hydrostatic Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Biomeng321Lab2", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Second Piola-Kirchhoff Stress Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Biomeng321Lab2", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Biomeng321Lab2", "(ref)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Biomeng321Lab2", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Biomeng321Lab2", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Biomeng321Lab2", "(fib)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Biomeng321Lab2", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Biomeng321Lab2", "Cauchy Stress Tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Biomeng321Lab2", "sigma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Biomeng321Lab2", "=", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.neon.ui.zincwidgets.sceneviewerwidget import SceneviewerWidget
