# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sceneviewereditorwidget.ui'
#
# Created: Tue Mar  8 11:53:10 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SceneviewerEditorWidget(object):
    def setupUi(self, SceneviewerEditorWidget):
        SceneviewerEditorWidget.setObjectName("SceneviewerEditorWidget")
        SceneviewerEditorWidget.resize(227, 689)
        self.verticalLayout = QtGui.QVBoxLayout(SceneviewerEditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view_all_button = QtGui.QPushButton(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_all_button.sizePolicy().hasHeightForWidth())
        self.view_all_button.setSizePolicy(sizePolicy)
        self.view_all_button.setObjectName("view_all_button")
        self.verticalLayout.addWidget(self.view_all_button)
        self.antialias_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.antialias_label.setObjectName("antialias_label")
        self.verticalLayout.addWidget(self.antialias_label)
        self.antialias = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antialias.sizePolicy().hasHeightForWidth())
        self.antialias.setSizePolicy(sizePolicy)
        self.antialias.setObjectName("antialias")
        self.verticalLayout.addWidget(self.antialias)
        self.perspective_checkbox = QtGui.QCheckBox(SceneviewerEditorWidget)
        self.perspective_checkbox.setChecked(True)
        self.perspective_checkbox.setObjectName("perspective_checkbox")
        self.verticalLayout.addWidget(self.perspective_checkbox)
        self.view_angle_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.view_angle_label.setObjectName("view_angle_label")
        self.verticalLayout.addWidget(self.view_angle_label)
        self.view_angle = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_angle.sizePolicy().hasHeightForWidth())
        self.view_angle.setSizePolicy(sizePolicy)
        self.view_angle.setObjectName("view_angle")
        self.verticalLayout.addWidget(self.view_angle)
        self.eye_position_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.eye_position_label.setObjectName("eye_position_label")
        self.verticalLayout.addWidget(self.eye_position_label)
        self.eye_position = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eye_position.sizePolicy().hasHeightForWidth())
        self.eye_position.setSizePolicy(sizePolicy)
        self.eye_position.setObjectName("eye_position")
        self.verticalLayout.addWidget(self.eye_position)
        self.lookat_position_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.lookat_position_label.setObjectName("lookat_position_label")
        self.verticalLayout.addWidget(self.lookat_position_label)
        self.lookat_position = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_position.sizePolicy().hasHeightForWidth())
        self.lookat_position.setSizePolicy(sizePolicy)
        self.lookat_position.setObjectName("lookat_position")
        self.verticalLayout.addWidget(self.lookat_position)
        self.up_vector_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.up_vector_label.setObjectName("up_vector_label")
        self.verticalLayout.addWidget(self.up_vector_label)
        self.up_vector = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_vector.sizePolicy().hasHeightForWidth())
        self.up_vector.setSizePolicy(sizePolicy)
        self.up_vector.setObjectName("up_vector")
        self.verticalLayout.addWidget(self.up_vector)
        self.clipping_planes_groupbox = QtGui.QGroupBox(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clipping_planes_groupbox.sizePolicy().hasHeightForWidth())
        self.clipping_planes_groupbox.setSizePolicy(sizePolicy)
        self.clipping_planes_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.clipping_planes_groupbox.setObjectName("clipping_planes_groupbox")
        self.formLayout = QtGui.QFormLayout(self.clipping_planes_groupbox)
        self.formLayout.setObjectName("formLayout")
        self.near_clipping_label = QtGui.QLabel(self.clipping_planes_groupbox)
        self.near_clipping_label.setObjectName("near_clipping_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.near_clipping_label)
        self.far_clipping_label = QtGui.QLabel(self.clipping_planes_groupbox)
        self.far_clipping_label.setObjectName("far_clipping_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.far_clipping_label)
        self.near_clipping_slider = QtGui.QSlider(self.clipping_planes_groupbox)
        self.near_clipping_slider.setMaximum(10000)
        self.near_clipping_slider.setPageStep(100)
        self.near_clipping_slider.setTracking(True)
        self.near_clipping_slider.setOrientation(QtCore.Qt.Horizontal)
        self.near_clipping_slider.setObjectName("near_clipping_slider")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.near_clipping_slider)
        self.far_clipping_slider = QtGui.QSlider(self.clipping_planes_groupbox)
        self.far_clipping_slider.setMaximum(10000)
        self.far_clipping_slider.setPageStep(100)
        self.far_clipping_slider.setOrientation(QtCore.Qt.Horizontal)
        self.far_clipping_slider.setObjectName("far_clipping_slider")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.far_clipping_slider)
        self.verticalLayout.addWidget(self.clipping_planes_groupbox)
        self.background_colour_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.background_colour_label.setObjectName("background_colour_label")
        self.verticalLayout.addWidget(self.background_colour_label)
        self.background_colour = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_colour.sizePolicy().hasHeightForWidth())
        self.background_colour.setSizePolicy(sizePolicy)
        self.background_colour.setObjectName("background_colour")
        self.verticalLayout.addWidget(self.background_colour)
        self.light_both_sides_checkbox = QtGui.QCheckBox(SceneviewerEditorWidget)
        self.light_both_sides_checkbox.setEnabled(True)
        self.light_both_sides_checkbox.setChecked(True)
        self.light_both_sides_checkbox.setObjectName("light_both_sides_checkbox")
        self.verticalLayout.addWidget(self.light_both_sides_checkbox)
        self.perturbline_checkbox = QtGui.QCheckBox(SceneviewerEditorWidget)
        self.perturbline_checkbox.setEnabled(True)
        self.perturbline_checkbox.setChecked(False)
        self.perturbline_checkbox.setObjectName("perturbline_checkbox")
        self.verticalLayout.addWidget(self.perturbline_checkbox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(SceneviewerEditorWidget)
        QtCore.QObject.connect(self.view_all_button, QtCore.SIGNAL("clicked()"), SceneviewerEditorWidget.viewAll)
        QtCore.QObject.connect(self.perspective_checkbox, QtCore.SIGNAL("clicked(bool)"), SceneviewerEditorWidget.perspectiveStateChanged)
        QtCore.QObject.connect(self.view_angle, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.viewAngleEntered)
        QtCore.QObject.connect(self.eye_position, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.eyePositionEntered)
        QtCore.QObject.connect(self.lookat_position, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.lookatPositionEntered)
        QtCore.QObject.connect(self.up_vector, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.upVectorEntered)
        QtCore.QObject.connect(self.near_clipping_slider, QtCore.SIGNAL("valueChanged(int)"), SceneviewerEditorWidget.nearClippingChanged)
        QtCore.QObject.connect(self.far_clipping_slider, QtCore.SIGNAL("valueChanged(int)"), SceneviewerEditorWidget.farClippingChanged)
        QtCore.QObject.connect(self.background_colour, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.backgroundColourEntered)
        QtCore.QObject.connect(self.antialias, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.antialiasEntered)
        QtCore.QObject.connect(self.perturbline_checkbox, QtCore.SIGNAL("clicked(bool)"), SceneviewerEditorWidget.perturbLineStateChanged)
        QtCore.QObject.connect(self.light_both_sides_checkbox, QtCore.SIGNAL("clicked(bool)"), SceneviewerEditorWidget.lightBothSidesStateChanged)
        QtCore.QMetaObject.connectSlotsByName(SceneviewerEditorWidget)

    def retranslateUi(self, SceneviewerEditorWidget):
        SceneviewerEditorWidget.setWindowTitle(QtGui.QApplication.translate("SceneviewerEditorWidget", "Sceneviewer Editor", None))
        self.view_all_button.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "View All", None))
        self.antialias_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Antialias:", None))
        self.perspective_checkbox.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Perspective projection", None))
        self.view_angle_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "View angle:", None))
        self.eye_position_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Eye position:", None))
        self.lookat_position_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Look at position:", None))
        self.up_vector_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Up vector:", None))
        self.clipping_planes_groupbox.setTitle(QtGui.QApplication.translate("SceneviewerEditorWidget", "Clipping planes:", None))
        self.near_clipping_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Near:", None))
        self.far_clipping_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Far:", None))
        self.background_colour_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Background colour R, G, B:", None))
        self.light_both_sides_checkbox.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Light Both Sides", None))
        self.perturbline_checkbox.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Perturb Line", None))

