# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/designer/spectrumeditorwidget.ui'
#
# Created: Tue Dec  8 13:59:46 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_SpectrumEditorWidget(object):
    def setupUi(self, SpectrumEditorWidget, shared_context):
        SpectrumEditorWidget.setObjectName("SpectrumEditorWidget")
        SpectrumEditorWidget.resize(281, 744)
        self.verticalLayout = QtGui.QVBoxLayout(SpectrumEditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(SpectrumEditorWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonDeleteSpectrum = QtGui.QPushButton(self.groupBox)
        self.pushButtonDeleteSpectrum.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/neon/images/icons/list-remove-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDeleteSpectrum.setIcon(icon)
        self.pushButtonDeleteSpectrum.setObjectName("pushButtonDeleteSpectrum")
        self.gridLayout.addWidget(self.pushButtonDeleteSpectrum, 1, 1, 1, 1)
        self.listWidgetSpectrums = QtGui.QListWidget(self.groupBox)
        self.listWidgetSpectrums.setObjectName("listWidgetSpectrums")
        self.gridLayout.addWidget(self.listWidgetSpectrums, 0, 0, 1, 3)
        self.pushButtonAddSpectrum = QtGui.QPushButton(self.groupBox)
        self.pushButtonAddSpectrum.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/neon/images/icons/list-add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddSpectrum.setIcon(icon1)
        self.pushButtonAddSpectrum.setObjectName("pushButtonAddSpectrum")
        self.gridLayout.addWidget(self.pushButtonAddSpectrum, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBoxSpectrumProperties = QtGui.QGroupBox(SpectrumEditorWidget)
        self.groupBoxSpectrumProperties.setObjectName("groupBoxSpectrumProperties")
        self.formLayout = QtGui.QFormLayout(self.groupBoxSpectrumProperties)
        self.formLayout.setObjectName("formLayout")
        self.checkBoxOverwrite = QtGui.QCheckBox(self.groupBoxSpectrumProperties)
        self.checkBoxOverwrite.setObjectName("checkBoxOverwrite")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBoxOverwrite)
        self.checkBoxDefault = QtGui.QCheckBox(self.groupBoxSpectrumProperties)
        self.checkBoxDefault.setObjectName("checkBoxDefault")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxDefault)
        self.verticalLayout.addWidget(self.groupBoxSpectrumProperties)
        self.groupBoxPreview = QtGui.QGroupBox(SpectrumEditorWidget)
        self.groupBoxPreview.setObjectName("groupBoxPreview")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBoxPreview)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = SceneviewerWidget(self.groupBoxPreview, shared_context)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addWidget(self.groupBoxPreview)
        self.groupBoxComponents = QtGui.QGroupBox(SpectrumEditorWidget)
        self.groupBoxComponents.setObjectName("groupBoxComponents")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxComponents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonMoveUpSpectrumComponent = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonMoveUpSpectrumComponent.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/neon/images/icons/go-up-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMoveUpSpectrumComponent.setIcon(icon2)
        self.pushButtonMoveUpSpectrumComponent.setObjectName("pushButtonMoveUpSpectrumComponent")
        self.gridLayout_2.addWidget(self.pushButtonMoveUpSpectrumComponent, 1, 3, 1, 1)
        self.listWidgetSpectrumComponents = QtGui.QListWidget(self.groupBoxComponents)
        self.listWidgetSpectrumComponents.setObjectName("listWidgetSpectrumComponents")
        self.gridLayout_2.addWidget(self.listWidgetSpectrumComponents, 0, 0, 1, 7)
        self.pushButtonAddSpectrumComponent = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonAddSpectrumComponent.setText("")
        self.pushButtonAddSpectrumComponent.setIcon(icon1)
        self.pushButtonAddSpectrumComponent.setObjectName("pushButtonAddSpectrumComponent")
        self.gridLayout_2.addWidget(self.pushButtonAddSpectrumComponent, 1, 0, 1, 1)
        self.pushButtonDeleteSpectrumComponent = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonDeleteSpectrumComponent.setText("")
        self.pushButtonDeleteSpectrumComponent.setIcon(icon)
        self.pushButtonDeleteSpectrumComponent.setObjectName("pushButtonDeleteSpectrumComponent")
        self.gridLayout_2.addWidget(self.pushButtonDeleteSpectrumComponent, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 5, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.pushButtonMoveDownSpectrumComponent = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonMoveDownSpectrumComponent.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/neon/images/icons/go-down-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMoveDownSpectrumComponent.setIcon(icon3)
        self.pushButtonMoveDownSpectrumComponent.setObjectName("pushButtonMoveDownSpectrumComponent")
        self.gridLayout_2.addWidget(self.pushButtonMoveDownSpectrumComponent, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxComponents)
        self.groupBoxComponentProperties = QtGui.QGroupBox(SpectrumEditorWidget)
        self.groupBoxComponentProperties.setObjectName("groupBoxComponentProperties")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBoxComponentProperties)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.groupBoxComponentProperties)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBoxColourMap = QtGui.QComboBox(self.groupBoxComponentProperties)
        self.comboBoxColourMap.setObjectName("comboBoxColourMap")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxColourMap)
        self.label_2 = QtGui.QLabel(self.groupBoxComponentProperties)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboBoxScale = QtGui.QComboBox(self.groupBoxComponentProperties)
        self.comboBoxScale.setObjectName("comboBoxScale")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxScale)
        self.label_3 = QtGui.QLabel(self.groupBoxComponentProperties)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spinBoxDataFieldComponent = QtGui.QSpinBox(self.groupBoxComponentProperties)
        self.spinBoxDataFieldComponent.setProperty("value", 1)
        self.spinBoxDataFieldComponent.setObjectName("spinBoxDataFieldComponent")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxDataFieldComponent)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBoxComponentProperties)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditNormalisedRangeMin = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditNormalisedRangeMin.setObjectName("lineEditNormalisedRangeMin")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNormalisedRangeMin)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditNormalisedRangeMax = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditNormalisedRangeMax.setObjectName("lineEditNormalisedRangeMax")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNormalisedRangeMax)
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.SpanningRole, self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBoxComponentProperties)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEditRangeMin = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditRangeMin.setObjectName("lineEditRangeMin")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditRangeMin)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEditRangeMax = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditRangeMax.setObjectName("lineEditRangeMax")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditRangeMax)
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.SpanningRole, self.groupBox_3)
        self.pushButtonAutorange = QtGui.QPushButton(self.groupBoxComponentProperties)
        self.pushButtonAutorange.setObjectName("pushButtonAutorange")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButtonAutorange)
        self.comboBoxScene = QtGui.QComboBox(self.groupBoxComponentProperties)
        self.comboBoxScene.setObjectName("comboBoxScene")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxScene)
        self.checkBoxReverse = QtGui.QCheckBox(self.groupBoxComponentProperties)
        self.checkBoxReverse.setObjectName("checkBoxReverse")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.checkBoxReverse)
        self.verticalLayout.addWidget(self.groupBoxComponentProperties)

        self.retranslateUi(SpectrumEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(SpectrumEditorWidget)

    def retranslateUi(self, SpectrumEditorWidget):
        SpectrumEditorWidget.setWindowTitle(QtGui.QApplication.translate("SpectrumEditorWidget", "Spectrum Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SpectrumEditorWidget", "Spectrums", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeleteSpectrum.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Remove spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddSpectrum.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Add spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSpectrumProperties.setTitle(QtGui.QApplication.translate("SpectrumEditorWidget", "Spectrum Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOverwrite.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Overwrite graphics material colour with spectrum colour", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOverwrite.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Overwrite", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDefault.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxPreview.setTitle(QtGui.QApplication.translate("SpectrumEditorWidget", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxComponents.setTitle(QtGui.QApplication.translate("SpectrumEditorWidget", "Components", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMoveUpSpectrumComponent.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Move component up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddSpectrumComponent.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Add component", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeleteSpectrumComponent.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Remove component", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMoveDownSpectrumComponent.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Move component down", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxComponentProperties.setTitle(QtGui.QApplication.translate("SpectrumEditorWidget", "Component Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Colour Map:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Index of component to use from data field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Data field comp.:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxDataFieldComponent.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Index of component to use from data field", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SpectrumEditorWidget", "Normalised Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Component to use from data field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditNormalisedRangeMin.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Component to use from data field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditNormalisedRangeMax.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SpectrumEditorWidget", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Component to use from data field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditRangeMin.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setToolTip(QtGui.QApplication.translate("SpectrumEditorWidget", "Component to use from data field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditRangeMax.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAutorange.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Autorange", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxReverse.setText(QtGui.QApplication.translate("SpectrumEditorWidget", "Reverse", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.neon.ui.zincwidgets.sceneviewerwidget import SceneviewerWidget
from opencmiss.neon.ui import icons_rc
