# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/designer/problems/ventilationwidget.ui'
#
# Created: Tue Jan  5 09:25:51 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_VentilationWidget(object):
    def setupUi(self, VentilationWidget):
        VentilationWidget.setObjectName("VentilationWidget")
        VentilationWidget.resize(720, 976)
        self.verticalLayout = QtGui.QVBoxLayout(VentilationWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(VentilationWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabExecutable = QtGui.QWidget()
        self.tabExecutable.setObjectName("tabExecutable")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabExecutable)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.tabExecutable)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxInBuiltExecutable = QtGui.QCheckBox(self.groupBox)
        self.checkBoxInBuiltExecutable.setObjectName("checkBoxInBuiltExecutable")
        self.gridLayout.addWidget(self.checkBoxInBuiltExecutable, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEditExecutable = QtGui.QLineEdit(self.groupBox)
        self.lineEditExecutable.setObjectName("lineEditExecutable")
        self.gridLayout.addWidget(self.lineEditExecutable, 1, 1, 1, 1)
        self.pushButtonChooseExecutable = QtGui.QPushButton(self.groupBox)
        self.pushButtonChooseExecutable.setObjectName("pushButtonChooseExecutable")
        self.gridLayout.addWidget(self.pushButtonChooseExecutable, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 766, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tabExecutable, "")
        self.tabFileInputs = QtGui.QWidget()
        self.tabFileInputs.setObjectName("tabFileInputs")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabFileInputs)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtGui.QGroupBox(self.tabFileInputs)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_7.addWidget(self.label_24)
        self.lineEditExElem = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditExElem.setObjectName("lineEditExElem")
        self.horizontalLayout_7.addWidget(self.lineEditExElem)
        self.pushButtonChooseExElem = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonChooseExElem.setObjectName("pushButtonChooseExElem")
        self.horizontalLayout_7.addWidget(self.pushButtonChooseExElem)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.lineEditExNode = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditExNode.setObjectName("lineEditExNode")
        self.horizontalLayout_6.addWidget(self.lineEditExNode)
        self.pushButtonChooseExNode = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonChooseExNode.setObjectName("pushButtonChooseExNode")
        self.horizontalLayout_6.addWidget(self.pushButtonChooseExNode)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.lineEditIpNode = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditIpNode.setObjectName("lineEditIpNode")
        self.horizontalLayout_3.addWidget(self.lineEditIpNode)
        self.pushButtonChooseIpNode = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonChooseIpNode.setObjectName("pushButtonChooseIpNode")
        self.horizontalLayout_3.addWidget(self.pushButtonChooseIpNode)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.lineEditIpField = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditIpField.setObjectName("lineEditIpField")
        self.horizontalLayout_5.addWidget(self.lineEditIpField)
        self.pushButtonChooseIpField = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonChooseIpField.setObjectName("pushButtonChooseIpField")
        self.horizontalLayout_5.addWidget(self.pushButtonChooseIpField)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.checkBoxInBuiltTree = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxInBuiltTree.setObjectName("checkBoxInBuiltTree")
        self.gridLayout_2.addWidget(self.checkBoxInBuiltTree, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.lineEditIpElem = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditIpElem.setObjectName("lineEditIpElem")
        self.horizontalLayout_4.addWidget(self.lineEditIpElem)
        self.pushButtonChooseIpElem = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonChooseIpElem.setObjectName("pushButtonChooseIpElem")
        self.horizontalLayout_4.addWidget(self.pushButtonChooseIpElem)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tabFileInputs)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBoxInBuiltFlow = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxInBuiltFlow.setObjectName("checkBoxInBuiltFlow")
        self.verticalLayout_4.addWidget(self.checkBoxInBuiltFlow)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_2.addWidget(self.label_25)
        self.lineEditFlow = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditFlow.setObjectName("lineEditFlow")
        self.horizontalLayout_2.addWidget(self.lineEditFlow)
        self.pushButtonChooseFlow = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonChooseFlow.setObjectName("pushButtonChooseFlow")
        self.horizontalLayout_2.addWidget(self.pushButtonChooseFlow)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tabFileInputs)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout.addWidget(self.label_26)
        self.lineEditOutExNode = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditOutExNode.setObjectName("lineEditOutExNode")
        self.horizontalLayout.addWidget(self.lineEditOutExNode)
        self.pushButtonChooseOutExNode = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonChooseOutExNode.setObjectName("pushButtonChooseOutExNode")
        self.horizontalLayout.addWidget(self.pushButtonChooseOutExNode)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.tabWidget.addTab(self.tabFileInputs, "")
        self.tabParameters = QtGui.QWidget()
        self.tabParameters.setObjectName("tabParameters")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabParameters)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxMainParameters = QtGui.QGroupBox(self.tabParameters)
        self.groupBoxMainParameters.setObjectName("groupBoxMainParameters")
        self.formLayout = QtGui.QFormLayout(self.groupBoxMainParameters)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBoxMainParameters)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.spinBoxNumberOfBreaths = QtGui.QSpinBox(self.groupBoxMainParameters)
        self.spinBoxNumberOfBreaths.setMinimum(1)
        self.spinBoxNumberOfBreaths.setProperty("value", 5)
        self.spinBoxNumberOfBreaths.setObjectName("spinBoxNumberOfBreaths")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxNumberOfBreaths)
        self.label_2 = QtGui.QLabel(self.groupBoxMainParameters)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBoxNumberOfIterations = QtGui.QSpinBox(self.groupBoxMainParameters)
        self.spinBoxNumberOfIterations.setMinimum(1)
        self.spinBoxNumberOfIterations.setMaximum(999999999)
        self.spinBoxNumberOfIterations.setSingleStep(100)
        self.spinBoxNumberOfIterations.setProperty("value", 200)
        self.spinBoxNumberOfIterations.setObjectName("spinBoxNumberOfIterations")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxNumberOfIterations)
        self.label_3 = QtGui.QLabel(self.groupBoxMainParameters)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.doubleSpinBoxTimeStep = ScientificDoubleSpinBox(self.groupBoxMainParameters)
        self.doubleSpinBoxTimeStep.setObjectName("doubleSpinBoxTimeStep")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxTimeStep)
        self.label_4 = QtGui.QLabel(self.groupBoxMainParameters)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.doubleSpinBoxErrorTolerance = ScientificDoubleSpinBox(self.groupBoxMainParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxErrorTolerance.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxErrorTolerance.setSizePolicy(sizePolicy)
        self.doubleSpinBoxErrorTolerance.setObjectName("doubleSpinBoxErrorTolerance")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxErrorTolerance)
        self.verticalLayout_2.addWidget(self.groupBoxMainParameters)
        self.groupBoxFlowParameters = QtGui.QGroupBox(self.tabParameters)
        self.groupBoxFlowParameters.setObjectName("groupBoxFlowParameters")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBoxFlowParameters)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.doubleSpinBoxFRC = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxFRC.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxFRC.setSizePolicy(sizePolicy)
        self.doubleSpinBoxFRC.setObjectName("doubleSpinBoxFRC")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxFRC)
        self.label_6 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.doubleSpinBoxConstrict = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxConstrict.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxConstrict.setSizePolicy(sizePolicy)
        self.doubleSpinBoxConstrict.setObjectName("doubleSpinBoxConstrict")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxConstrict)
        self.label_7 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.doubleSpinBoxTInterval = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxTInterval.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxTInterval.setSizePolicy(sizePolicy)
        self.doubleSpinBoxTInterval.setObjectName("doubleSpinBoxTInterval")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxTInterval)
        self.label_8 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_8)
        self.spinBoxGdirn = QtGui.QSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxGdirn.sizePolicy().hasHeightForWidth())
        self.spinBoxGdirn.setSizePolicy(sizePolicy)
        self.spinBoxGdirn.setMinimum(1)
        self.spinBoxGdirn.setObjectName("spinBoxGdirn")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.spinBoxGdirn)
        self.label_9 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.doubleSpinBoxPressIn = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPressIn.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPressIn.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPressIn.setObjectName("doubleSpinBoxPressIn")
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxPressIn)
        self.label_10 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_10)
        self.doubleSpinBoxCOV = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxCOV.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxCOV.setSizePolicy(sizePolicy)
        self.doubleSpinBoxCOV.setObjectName("doubleSpinBoxCOV")
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxCOV)
        self.label_11 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_11)
        self.doubleSpinBoxRMaxMean = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRMaxMean.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRMaxMean.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRMaxMean.setObjectName("doubleSpinBoxRMaxMean")
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxRMaxMean)
        self.label_12 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_12)
        self.doubleSpinBoxRMinMean = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRMinMean.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRMinMean.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRMinMean.setObjectName("doubleSpinBoxRMinMean")
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxRMinMean)
        self.label_13 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(16, QtGui.QFormLayout.LabelRole, self.label_13)
        self.doubleSpinBoxIERatio = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxIERatio.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxIERatio.setSizePolicy(sizePolicy)
        self.doubleSpinBoxIERatio.setObjectName("doubleSpinBoxIERatio")
        self.formLayout_2.setWidget(16, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxIERatio)
        self.label_18 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.LabelRole, self.label_18)
        self.doubleSpinBoxRefVolume = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRefVolume.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRefVolume.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRefVolume.setObjectName("doubleSpinBoxRefVolume")
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxRefVolume)
        self.label_14 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(20, QtGui.QFormLayout.LabelRole, self.label_14)
        self.doubleSpinBoxVolumeTarget = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxVolumeTarget.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxVolumeTarget.setSizePolicy(sizePolicy)
        self.doubleSpinBoxVolumeTarget.setObjectName("doubleSpinBoxVolumeTarget")
        self.formLayout_2.setWidget(20, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxVolumeTarget)
        self.label_15 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(22, QtGui.QFormLayout.LabelRole, self.label_15)
        self.doubleSpinBoxPMusStep = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPMusStep.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPMusStep.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPMusStep.setMinimum(-9999999.99)
        self.doubleSpinBoxPMusStep.setObjectName("doubleSpinBoxPMusStep")
        self.formLayout_2.setWidget(22, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxPMusStep)
        self.label_17 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(24, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_16 = QtGui.QLabel(self.groupBoxFlowParameters)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(26, QtGui.QFormLayout.LabelRole, self.label_16)
        self.doubleSpinBoxChestWallCompliance = ScientificDoubleSpinBox(self.groupBoxFlowParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxChestWallCompliance.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxChestWallCompliance.setSizePolicy(sizePolicy)
        self.doubleSpinBoxChestWallCompliance.setObjectName("doubleSpinBoxChestWallCompliance")
        self.formLayout_2.setWidget(26, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxChestWallCompliance)
        self.comboBoxExpirationType = QtGui.QComboBox(self.groupBoxFlowParameters)
        self.comboBoxExpirationType.setObjectName("comboBoxExpirationType")
        self.comboBoxExpirationType.addItem("")
        self.formLayout_2.setWidget(24, QtGui.QFormLayout.FieldRole, self.comboBoxExpirationType)
        self.verticalLayout_2.addWidget(self.groupBoxFlowParameters)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.tabWidget.addTab(self.tabParameters, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(VentilationWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(VentilationWidget)
        VentilationWidget.setTabOrder(self.spinBoxNumberOfBreaths, self.spinBoxNumberOfIterations)
        VentilationWidget.setTabOrder(self.spinBoxNumberOfIterations, self.doubleSpinBoxTimeStep)
        VentilationWidget.setTabOrder(self.doubleSpinBoxTimeStep, self.doubleSpinBoxErrorTolerance)
        VentilationWidget.setTabOrder(self.doubleSpinBoxErrorTolerance, self.doubleSpinBoxFRC)
        VentilationWidget.setTabOrder(self.doubleSpinBoxFRC, self.doubleSpinBoxConstrict)
        VentilationWidget.setTabOrder(self.doubleSpinBoxConstrict, self.doubleSpinBoxTInterval)
        VentilationWidget.setTabOrder(self.doubleSpinBoxTInterval, self.spinBoxGdirn)
        VentilationWidget.setTabOrder(self.spinBoxGdirn, self.doubleSpinBoxPressIn)
        VentilationWidget.setTabOrder(self.doubleSpinBoxPressIn, self.doubleSpinBoxCOV)
        VentilationWidget.setTabOrder(self.doubleSpinBoxCOV, self.doubleSpinBoxRMaxMean)
        VentilationWidget.setTabOrder(self.doubleSpinBoxRMaxMean, self.doubleSpinBoxRMinMean)
        VentilationWidget.setTabOrder(self.doubleSpinBoxRMinMean, self.doubleSpinBoxIERatio)
        VentilationWidget.setTabOrder(self.doubleSpinBoxIERatio, self.doubleSpinBoxRefVolume)
        VentilationWidget.setTabOrder(self.doubleSpinBoxRefVolume, self.doubleSpinBoxVolumeTarget)
        VentilationWidget.setTabOrder(self.doubleSpinBoxVolumeTarget, self.doubleSpinBoxPMusStep)
        VentilationWidget.setTabOrder(self.doubleSpinBoxPMusStep, self.comboBoxExpirationType)
        VentilationWidget.setTabOrder(self.comboBoxExpirationType, self.doubleSpinBoxChestWallCompliance)

    def retranslateUi(self, VentilationWidget):
        VentilationWidget.setWindowTitle(QtGui.QApplication.translate("VentilationWidget", "Ventilation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("VentilationWidget", "Executable", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInBuiltExecutable.setText(QtGui.QApplication.translate("VentilationWidget", "Use in-built executable", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("VentilationWidget", "Executable:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseExecutable.setText(QtGui.QApplication.translate("VentilationWidget", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExecutable), QtGui.QApplication.translate("VentilationWidget", "Executable", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("VentilationWidget", "Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("VentilationWidget", "exelem:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseExElem.setText(QtGui.QApplication.translate("VentilationWidget", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("VentilationWidget", "exnode:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseExNode.setText(QtGui.QApplication.translate("VentilationWidget", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("VentilationWidget", "ipnode:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseIpNode.setText(QtGui.QApplication.translate("VentilationWidget", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("VentilationWidget", "ipfiel:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseIpField.setText(QtGui.QApplication.translate("VentilationWidget", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInBuiltTree.setText(QtGui.QApplication.translate("VentilationWidget", "Use in-built tree files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("VentilationWidget", "ipelem:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseIpElem.setText(QtGui.QApplication.translate("VentilationWidget", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("VentilationWidget", "Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInBuiltFlow.setText(QtGui.QApplication.translate("VentilationWidget", "Use in-built flow file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("VentilationWidget", "Executable:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseFlow.setText(QtGui.QApplication.translate("VentilationWidget", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("VentilationWidget", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("VentilationWidget", "Out exnode:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseOutExNode.setText(QtGui.QApplication.translate("VentilationWidget", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFileInputs), QtGui.QApplication.translate("VentilationWidget", "File Input/Output(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMainParameters.setTitle(QtGui.QApplication.translate("VentilationWidget", "Main Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VentilationWidget", "Number of breaths:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("VentilationWidget", "Number of iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("VentilationWidget", "dt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VentilationWidget", "Error tolerance:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxFlowParameters.setTitle(QtGui.QApplication.translate("VentilationWidget", "Flow Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("VentilationWidget", "FRC:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("VentilationWidget", "Constrict:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("VentilationWidget", "T interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("VentilationWidget", "G dirn:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("VentilationWidget", "Press in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("VentilationWidget", "COV:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("VentilationWidget", "R max. mean:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("VentilationWidget", "R min. mean:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("VentilationWidget", "i-e ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("VentilationWidget", "Ref. volume:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("VentilationWidget", "Volume target:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("VentilationWidget", "Pmus step:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("VentilationWidget", "Expiration type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("VentilationWidget", "Chest wall compliance:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxExpirationType.setItemText(0, QtGui.QApplication.translate("VentilationWidget", "Passive", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParameters), QtGui.QApplication.translate("VentilationWidget", "Parameters", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.neon.ui.misc.scientificdoublespinbox import ScientificDoubleSpinBox
