# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/designer/ventilationwidget.ui'
#
# Created: Thu Dec 24 09:53:36 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_VenitlationWidget(object):
    def setupUi(self, VenitlationWidget):
        VenitlationWidget.setObjectName("VenitlationWidget")
        VenitlationWidget.resize(666, 913)
        self.verticalLayout = QtGui.QVBoxLayout(VenitlationWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(VenitlationWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.spinBoxNumberOfBreaths = QtGui.QSpinBox(self.groupBox)
        self.spinBoxNumberOfBreaths.setMinimum(1)
        self.spinBoxNumberOfBreaths.setProperty("value", 5)
        self.spinBoxNumberOfBreaths.setObjectName("spinBoxNumberOfBreaths")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxNumberOfBreaths)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBoxNumberOfIterations = QtGui.QSpinBox(self.groupBox)
        self.spinBoxNumberOfIterations.setMinimum(1)
        self.spinBoxNumberOfIterations.setMaximum(999999999)
        self.spinBoxNumberOfIterations.setSingleStep(100)
        self.spinBoxNumberOfIterations.setProperty("value", 200)
        self.spinBoxNumberOfIterations.setObjectName("spinBoxNumberOfIterations")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxNumberOfIterations)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.doubleSpinBoxTimeStep = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxTimeStep.setDecimals(5)
        self.doubleSpinBoxTimeStep.setMaximum(9999999.99)
        self.doubleSpinBoxTimeStep.setSingleStep(0.01)
        self.doubleSpinBoxTimeStep.setProperty("value", 0.05)
        self.doubleSpinBoxTimeStep.setObjectName("doubleSpinBoxTimeStep")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxTimeStep)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.doubleSpinBoxErrorTolerance = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxErrorTolerance.setDecimals(15)
        self.doubleSpinBoxErrorTolerance.setMaximum(9999999.99)
        self.doubleSpinBoxErrorTolerance.setSingleStep(0.0)
        self.doubleSpinBoxErrorTolerance.setProperty("value", 1e-06)
        self.doubleSpinBoxErrorTolerance.setObjectName("doubleSpinBoxErrorTolerance")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxErrorTolerance)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(VenitlationWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.doubleSpinBoxFRC = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxFRC.setDecimals(5)
        self.doubleSpinBoxFRC.setMaximum(9999999.99)
        self.doubleSpinBoxFRC.setSingleStep(0.1)
        self.doubleSpinBoxFRC.setProperty("value", 3.6)
        self.doubleSpinBoxFRC.setObjectName("doubleSpinBoxFRC")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxFRC)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.doubleSpinBoxConstrict = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxConstrict.setDecimals(5)
        self.doubleSpinBoxConstrict.setMaximum(9999999.99)
        self.doubleSpinBoxConstrict.setSingleStep(0.1)
        self.doubleSpinBoxConstrict.setProperty("value", 1.0)
        self.doubleSpinBoxConstrict.setObjectName("doubleSpinBoxConstrict")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxConstrict)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.doubleSpinBoxTInterval = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxTInterval.setDecimals(5)
        self.doubleSpinBoxTInterval.setMaximum(9999999.99)
        self.doubleSpinBoxTInterval.setSingleStep(0.1)
        self.doubleSpinBoxTInterval.setProperty("value", 4.0)
        self.doubleSpinBoxTInterval.setObjectName("doubleSpinBoxTInterval")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxTInterval)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_8)
        self.spinBoxGdirn = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxGdirn.setMinimum(1)
        self.spinBoxGdirn.setProperty("value", 3)
        self.spinBoxGdirn.setObjectName("spinBoxGdirn")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.spinBoxGdirn)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.doubleSpinBoxPressIn = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxPressIn.setDecimals(5)
        self.doubleSpinBoxPressIn.setMaximum(9999999.99)
        self.doubleSpinBoxPressIn.setSingleStep(0.1)
        self.doubleSpinBoxPressIn.setObjectName("doubleSpinBoxPressIn")
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxPressIn)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_10)
        self.doubleSpinBoxCOV = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxCOV.setDecimals(5)
        self.doubleSpinBoxCOV.setMaximum(9999999.99)
        self.doubleSpinBoxCOV.setSingleStep(0.1)
        self.doubleSpinBoxCOV.setProperty("value", 0.2)
        self.doubleSpinBoxCOV.setObjectName("doubleSpinBoxCOV")
        self.formLayout_2.setWidget(10, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxCOV)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_11)
        self.doubleSpinBoxRMaxMean = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxRMaxMean.setDecimals(5)
        self.doubleSpinBoxRMaxMean.setMaximum(9999999.99)
        self.doubleSpinBoxRMaxMean.setSingleStep(0.01)
        self.doubleSpinBoxRMaxMean.setProperty("value", 1.29)
        self.doubleSpinBoxRMaxMean.setObjectName("doubleSpinBoxRMaxMean")
        self.formLayout_2.setWidget(12, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxRMaxMean)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_12)
        self.doubleSpinBoxRMinMean = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxRMinMean.setDecimals(5)
        self.doubleSpinBoxRMinMean.setMaximum(9999999.99)
        self.doubleSpinBoxRMinMean.setSingleStep(0.01)
        self.doubleSpinBoxRMinMean.setProperty("value", 0.78)
        self.doubleSpinBoxRMinMean.setObjectName("doubleSpinBoxRMinMean")
        self.formLayout_2.setWidget(14, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxRMinMean)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(16, QtGui.QFormLayout.LabelRole, self.label_13)
        self.doubleSpinBoxIERatio = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxIERatio.setDecimals(5)
        self.doubleSpinBoxIERatio.setMaximum(9999999.99)
        self.doubleSpinBoxIERatio.setSingleStep(0.1)
        self.doubleSpinBoxIERatio.setProperty("value", 0.5)
        self.doubleSpinBoxIERatio.setObjectName("doubleSpinBoxIERatio")
        self.formLayout_2.setWidget(16, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxIERatio)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.LabelRole, self.label_18)
        self.doubleSpinBoxRefVolume = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxRefVolume.setDecimals(5)
        self.doubleSpinBoxRefVolume.setMaximum(9999999.99)
        self.doubleSpinBoxRefVolume.setSingleStep(0.1)
        self.doubleSpinBoxRefVolume.setProperty("value", 0.6)
        self.doubleSpinBoxRefVolume.setObjectName("doubleSpinBoxRefVolume")
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxRefVolume)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(20, QtGui.QFormLayout.LabelRole, self.label_14)
        self.doubleSpinBoxVolumeTarget = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxVolumeTarget.setDecimals(5)
        self.doubleSpinBoxVolumeTarget.setMaximum(9999999.99)
        self.doubleSpinBoxVolumeTarget.setSingleStep(0.1)
        self.doubleSpinBoxVolumeTarget.setProperty("value", 80000.0)
        self.doubleSpinBoxVolumeTarget.setObjectName("doubleSpinBoxVolumeTarget")
        self.formLayout_2.setWidget(20, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxVolumeTarget)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(22, QtGui.QFormLayout.LabelRole, self.label_15)
        self.doubleSpinBoxPMusStep = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxPMusStep.setDecimals(5)
        self.doubleSpinBoxPMusStep.setMinimum(-9999999.99)
        self.doubleSpinBoxPMusStep.setMaximum(9999999.99)
        self.doubleSpinBoxPMusStep.setSingleStep(0.1)
        self.doubleSpinBoxPMusStep.setProperty("value", -529.559)
        self.doubleSpinBoxPMusStep.setObjectName("doubleSpinBoxPMusStep")
        self.formLayout_2.setWidget(22, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxPMusStep)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(24, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(26, QtGui.QFormLayout.LabelRole, self.label_16)
        self.doubleSpinBoxChestWallCompliance = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxChestWallCompliance.setDecimals(5)
        self.doubleSpinBoxChestWallCompliance.setMaximum(9999999.99)
        self.doubleSpinBoxChestWallCompliance.setSingleStep(1.0)
        self.doubleSpinBoxChestWallCompliance.setProperty("value", 2039.4324)
        self.doubleSpinBoxChestWallCompliance.setObjectName("doubleSpinBoxChestWallCompliance")
        self.formLayout_2.setWidget(26, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxChestWallCompliance)
        self.comboBoxExpirationType = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxExpirationType.setObjectName("comboBoxExpirationType")
        self.comboBoxExpirationType.addItem("")
        self.formLayout_2.setWidget(24, QtGui.QFormLayout.FieldRole, self.comboBoxExpirationType)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(VenitlationWidget)
        QtCore.QMetaObject.connectSlotsByName(VenitlationWidget)
        VenitlationWidget.setTabOrder(self.spinBoxNumberOfBreaths, self.spinBoxNumberOfIterations)
        VenitlationWidget.setTabOrder(self.spinBoxNumberOfIterations, self.doubleSpinBoxTimeStep)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxTimeStep, self.doubleSpinBoxErrorTolerance)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxErrorTolerance, self.doubleSpinBoxFRC)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxFRC, self.doubleSpinBoxConstrict)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxConstrict, self.doubleSpinBoxTInterval)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxTInterval, self.spinBoxGdirn)
        VenitlationWidget.setTabOrder(self.spinBoxGdirn, self.doubleSpinBoxPressIn)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxPressIn, self.doubleSpinBoxCOV)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxCOV, self.doubleSpinBoxRMaxMean)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxRMaxMean, self.doubleSpinBoxRMinMean)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxRMinMean, self.doubleSpinBoxIERatio)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxIERatio, self.doubleSpinBoxRefVolume)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxRefVolume, self.doubleSpinBoxVolumeTarget)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxVolumeTarget, self.doubleSpinBoxPMusStep)
        VenitlationWidget.setTabOrder(self.doubleSpinBoxPMusStep, self.comboBoxExpirationType)
        VenitlationWidget.setTabOrder(self.comboBoxExpirationType, self.doubleSpinBoxChestWallCompliance)

    def retranslateUi(self, VenitlationWidget):
        VenitlationWidget.setWindowTitle(QtGui.QApplication.translate("VenitlationWidget", "Ventilation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("VenitlationWidget", "Main Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VenitlationWidget", "Number of breaths:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("VenitlationWidget", "Number of iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("VenitlationWidget", "dt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VenitlationWidget", "Error tolerance:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("VenitlationWidget", "Flow Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("VenitlationWidget", "FRC:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("VenitlationWidget", "Constrict:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("VenitlationWidget", "T interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("VenitlationWidget", "G dirn:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("VenitlationWidget", "Press in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("VenitlationWidget", "COV:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("VenitlationWidget", "R max. mean:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("VenitlationWidget", "R min. mean:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("VenitlationWidget", "i-e ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("VenitlationWidget", "Ref. volume:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("VenitlationWidget", "Volume target:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("VenitlationWidget", "Pmus step:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("VenitlationWidget", "Expiration type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("VenitlationWidget", "Chest wall compliance:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxExpirationType.setItemText(0, QtGui.QApplication.translate("VenitlationWidget", "Passive", None, QtGui.QApplication.UnicodeUTF8))

